version: "3.9"

services:
  app:
    build: ./app/
    depends_on:
      - mongodb
    links:
      - mongodb
    volumes:
      - C:\Users\Yevhe\Desktop\Python\DB labs\lab4\app:/app
  
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
